import { ArrowLeft, ArrowRight, BadgeCheck, Camera, Check, KeyRound, Mail, ShieldCheck, UserRound } from 'lucide-react';
import { Logo } from '../../_components/site-shell';

const copy:Record<string,{eyebrow:string;title:string;text:string}>={
 'register-client':{eyebrow:'Новый клиент',title:'Создайте личный кабинет',text:'Сохраняйте фотографов, управляйте заказами и получайте готовые фотографии в одном месте.'},
 'register-photographer':{eyebrow:'Для фотографов',title:'Начните принимать заказы',text:'Создайте профиль, добавьте услуги и откройте свободные даты в календаре.'},
 verify:{eyebrow:'Подтверждение почты',title:'Проверьте входящие',text:'Мы отправили шестизначный код на roman@proskurnin.ru.'},
 link:{eyebrow:'Безопасный вход',title:'Ссылка подтверждена',text:'Вы вошли в ФотоЗаку. Выберите, куда перейти дальше.'},
 role:{eyebrow:'Один последний шаг',title:'Как вы будете использовать ФотоЗаку?',text:'Роль можно дополнить позже в настройках аккаунта.'},
};

export default async function AuthStepPage({params}:{params:Promise<{step:string}>}){const {step}=await params;const c=copy[step]||copy['register-client'];const verify=step==='verify';const role=step==='role';const success=step==='link';return <main className="auth-flow"><header className="auth-flow-head"><Logo/><a href="/login"><ArrowLeft/>Вернуться ко входу</a></header><section className="auth-flow-card"><span className="eyebrow"><KeyRound/>{c.eyebrow}</span><h1>{c.title}</h1><p>{c.text}</p>{success?<div className="auth-success"><span><Check/></span><a href="/dashboard/client">Перейти в кабинет клиента <ArrowRight/></a><a href="/dashboard/photographer">Перейти в кабинет фотографа <ArrowRight/></a></div>:role?<div className="role-cards"><a href="/dashboard/client"><UserRound/><b>Я ищу фотографа</b><small>Заказы, избранное и готовые галереи</small><ArrowRight/></a><a href="/dashboard/photographer/onboarding"><Camera/><b>Я фотограф</b><small>Профиль, календарь и новые клиенты</small><ArrowRight/></a></div>:verify?<form className="auth-code"><div>{[0,1,2,3,4,5].map(i=><input aria-label={`Цифра ${i+1}`} inputMode="numeric" maxLength={1} key={i}/>)}</div><a href="/auth/role">Подтвердить код <ArrowRight/></a><button type="button">Отправить код ещё раз</button></form>:<form className="auth-register"><label>Имя<input placeholder="Как к вам обращаться"/></label><label>Электронная почта<div><Mail/><input type="email" placeholder="name@example.ru"/></div></label><label>Телефон<input placeholder="+7 999 000-00-00"/></label><label className="consent"><input type="checkbox"/>Согласен с условиями сервиса и политикой конфиденциальности</label><a href="/auth/verify">Продолжить <ArrowRight/></a></form>}<footer><ShieldCheck/>Данные защищены и не передаются фотографам до подтверждения заказа.</footer></section></main>}
