'use client';

import { useState } from 'react';
import { CalendarDays, Camera, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, Images, MessageCircle, Plus, Settings, Star, Users } from 'lucide-react';
import { Logo } from '../../_components/site-shell';

export default function PhotographerDashboard() {
  const [view, setView] = useState('Неделя');
  return <main className="dashboard-page photographer-dash"><aside className="dash-sidebar"><Logo/><nav><a className="active" href="#"><CalendarDays/>Календарь</a><a href="#"><Users/>Клиенты</a><a href="#"><MessageCircle/>Сообщения <i>3</i></a><a href="#"><CircleDollarSign/>Финансы</a><a href="/gallery/demo"><Images/>Галереи <small>скоро</small></a><a href="/photographers/alina-vetrova"><Camera/>Мой профиль</a></nav><div className="sidebar-bottom"><a href="#"><Settings/>Настройки</a><div className="user-mini"><span>АВ</span><div><b>Алина Ветрова</b><small>Фотограф · 4,98 ★</small></div></div></div></aside>
    <section className="dash-content"><header className="dash-top"><div><span>Кабинет фотографа</span><h1>Календарь</h1></div><button><Plus size={17}/> Добавить съёмку</button></header><section className="stats-row"><article><span>На этой неделе</span><strong>6 съёмок</strong><small>+2 к прошлой неделе</small></article><article><span>К выплате</span><strong>48 500 ₽</strong><small>ближайшая — 8 сентября</small></article><article><span>Новые заявки</span><strong>3</strong><small>ожидают ответа</small></article><article><span>Рейтинг</span><strong>4,98 <Star size={18} fill="currentColor"/></strong><small>86 отзывов</small></article></section>
      <section className="work-calendar"><header><div className="cal-controls"><button><ChevronLeft/></button><button><ChevronRight/></button><b>7–13 сентября 2026</b><button>Сегодня</button></div><div className="view-tabs">{['День','Неделя','Месяц'].map((item) => <button className={view===item?'active':''} onClick={() => setView(item)} key={item}>{item}</button>)}</div></header><div className="calendar-board"><div className="cal-time"><span>09:00</span><span>11:00</span><span>13:00</span><span>15:00</span><span>17:00</span><span>19:00</span></div>{['Пн 7','Вт 8','Ср 9','Чт 10','Пт 11','Сб 12','Вс 13'].map((day,i) => <div className={`cal-day ${i===2?'today':''}`} key={day}><b>{day}</b>{i===0&&<div className="cal-event coral" style={{top:70,height:95}}><small>10:30</small><strong>Love story</strong><span>Чистые пруды</span></div>}{i===1&&<div className="cal-event green" style={{top:190,height:110}}><small>13:00</small><strong>Контент</strong><span>Студия 18</span></div>}{i===2&&<><div className="cal-event blue" style={{top:130,height:85}}><small>12:00</small><strong>Портрет</strong><span>Хлебозавод</span></div><div className="cal-event request" style={{top:300,height:95}}><small>16:00 · заявка</small><strong>Семейная</strong><span>Нужно ответить</span></div></>}{i===4&&<div className="cal-event sand" style={{top:245,height:125}}><small>15:00</small><strong>Свадьба</strong><span>ЗАГС №1</span></div>}{i===5&&<div className="cal-event coral" style={{top:45,height:95}}><small>09:30</small><strong>Прогулка</strong><span>Коломенское</span></div>}</div>)}</div></section>
    </section></main>;
}
