import { ArrowRight, Award, BadgeCheck, Heart, Sparkles, Star } from 'lucide-react';
import { PhotoCard } from '../_components/photo-card';
import { SiteFooter, SiteHeader } from '../_components/site-shell';
import { photographers } from '../data';

export default function CollectionsPage(){return <main><SiteHeader compact/><section className="collection-hero shell"><div><span className="eyebrow"><Sparkles/>Выбор редакции</span><h1>Не рейтинг популярности.<br/><em>Работы, которые говорят.</em></h1><p>Каждую подборку собирает редакция ФотоЗаки: смотрим целые серии, стабильность результата и отзывы подтверждённых клиентов.</p></div><div className="editorial-cover mosaic-photo"><span><Award/>Выбор сентября</span></div></section>
 <section className="collection-list shell"><a className="feature-collection" href="/search"><div className="feature-photo mosaic-photo"/><div><span>01 · Сентябрь 2026</span><h2>Живой портрет:<br/>минимум постановки</h2><p>12 фотографов, которые умеют оставить человеку свободу и поймать настоящий момент.</p><small>Собрала Мария Ярцева, фоторедактор</small><b>Смотреть подборку <ArrowRight/></b></div></a>
 <div className="small-collections"><a href="/shoots"><div className="mosaic-photo c-one"/><span>Для двоих</span><h3>Love story без клише</h3><p>8 фотографов · Москва</p></a><a href="/locations"><div className="mosaic-photo c-two"/><span>Новые места</span><h3>Город после дождя</h3><p>6 локаций · 14 сценариев</p></a><a href="/search"><div className="mosaic-photo c-three"/><span>Контент</span><h3>Сильный личный бренд</h3><p>10 фотографов · от 9 000 ₽</p></a></div></section>
 <section className="award-block"><div className="shell"><Award/><div><span className="kicker">Знак качества</span><h2>Как попасть в выбор редакции</h2><p>Мы не продаём место в подборках. Учитываем серии работ, оценки клиентов, соблюдение сроков и отсутствие изменений цены после брони.</p></div><ul><li><BadgeCheck/>Портфолио проверено</li><li><Star/>Рейтинг от 4,8</li><li><Heart/>Не менее 20 завершённых съёмок</li></ul></div></section>
 <section className="location-photographers shell"><div className="section-heading"><div><span className="kicker">Выбор сентября</span><h2>Фотографы редакции</h2></div></div><div className="cards-grid">{photographers.slice(0,3).map((p)=><PhotoCard person={p} key={p.slug}/>)}</div></section><SiteFooter/></main>}
