import { AlertTriangle, BadgeCheck, Banknote, BookOpenText, Check, CircleSlash2, Download, Eye, Flag, MapPin, MessageSquareWarning, Plus, Search, ShieldAlert, Star, UserRoundCheck, Users } from 'lucide-react';
import { AdminShell, RiskBadge } from '../../_components/admin-shell';
import { DataTable, MetricCards } from '../../_components/portal-shell';

const names:Record<string,string>={moderation:'Модерация фотографов',photographers:'Фотографы',users:'Клиенты',orders:'Заказы',disputes:'Споры и жалобы',reviews:'Отзывы',locations:'Локации',collections:'Контент и подборки',finance:'Финансы',promotions:'Продвижение',reports:'Отчёты',settings:'Настройки системы','audit-log':'Журнал действий'};

function Toolbar({placeholder='Поиск',button}:{placeholder?:string;button?:string}){return <div className="admin-toolbar"><label><Search/><input placeholder={placeholder}/></label><select><option>Все статусы</option><option>Активные</option><option>На проверке</option><option>Заблокированные</option></select>{button&&<button><Plus/>{button}</button>}</div>}

function AdminContent({section}:{section:string}){
 if(section==='moderation') return <><MetricCards items={[{label:'Новые анкеты',value:'12',note:'4 поступили сегодня',tone:'coral'},{label:'Изменения профиля',value:'7',note:'ожидают проверки'},{label:'Среднее время',value:'11 ч',note:'цель — до 24 часов',tone:'green'}]}/><section className="moderation-layout"><aside className="moderation-queue"><header><h2>Очередь</h2><span>19</span></header>{['Виктория Лебедева','Никита Орлов','София Миронова','Артём Беляев'].map((n,i)=><button className={i===0?'active':''} key={n}><span>{n.split(' ').map(x=>x[0]).join('')}</span><div><b>{n}</b><small>{i===0?'Новая анкета · 2 ч':'Изменения профиля'}</small></div><i>{i===0?'новое':''}</i></button>)}</aside><article className="moderation-preview portal-panel"><div className="moderation-cover mosaic-photo"/><div className="moderation-person"><span>ВЛ</span><div><h2>Виктория Лебедева</h2><p>Портрет · Семейная · Москва</p></div><RiskBadge tone="warning">Проверка</RiskBadge></div><div className="moderation-checks"><span><Check/>Телефон подтверждён</span><span><Check/>Паспорт проверен</span><span><AlertTriangle/>Нужно проверить права на фото</span></div><section><h3>О себе</h3><p>Снимаю живые семейные истории и помогаю чувствовать себя свободно перед камерой.</p></section><footer><button className="reject"><CircleSlash2/>Вернуть на доработку</button><button className="approve"><BadgeCheck/>Одобрить профиль</button></footer></article></section></>;
 if(section==='photographers') return <><Toolbar placeholder="Имя, город или специализация" button="Пригласить фотографа"/><MetricCards items={[{label:'Всего фотографов',value:'412',note:'327 активны'},{label:'Проверенные',value:'286',note:'69% каталога',tone:'green'},{label:'Приостановлены',value:'14',note:'6 требуют решения'},{label:'Средний рейтинг',value:'4,87',note:'по завершённым заказам'}]}/><section className="portal-panel"><DataTable columns={['Фотограф','Город','Заказов','Рейтинг','Статус','Комиссия']} rows={[[<b>Алина Ветрова</b>,'Москва','214','4,98',<RiskBadge tone="success">Проверен</RiskBadge>,'8%'],[<b>Максим Корнеев</b>,'Москва','186','4,94',<RiskBadge tone="success">Проверен</RiskBadge>,'8%'],[<b>Виктория Лебедева</b>,'Москва','0','—',<RiskBadge tone="warning">Модерация</RiskBadge>,'8%'],[<b>Артём Беляев</b>,'Санкт-Петербург','48','4,72',<RiskBadge>Активен</RiskBadge>,'10%']]}/></section></>;
 if(section==='users') return <><Toolbar placeholder="Имя, почта или телефон"/><MetricCards items={[{label:'Всего клиентов',value:'1 284',note:'+89 за неделю',tone:'green'},{label:'С заказами',value:'742',note:'58% пользователей'},{label:'Повторные',value:'31%',note:'сделали 2+ заказа'},{label:'Ограничены',value:'6',note:'из-за жалоб'}]}/><section className="portal-panel"><DataTable columns={['Клиент','Контакты','Заказов','Рейтинг','Регистрация','Статус']} rows={[[<b>Роман Проскурнин</b>,'roman@proskurnin.ru','3','4,9','28 мая',<RiskBadge tone="success">Активен</RiskBadge>],[<b>Екатерина Волкова</b>,'ekaterina@example.ru','5','5,0','12 апреля',<RiskBadge tone="success">Активен</RiskBadge>],[<b>Олег Николаев</b>,'oleg@example.ru','1','3,8','1 сентября',<RiskBadge tone="danger">Ограничен</RiskBadge>]]}/></section></>;
 if(section==='orders') return <><Toolbar placeholder="Номер, клиент или фотограф"/><MetricCards items={[{label:'Оборот за месяц',value:'1,84 млн ₽',note:'+24%',tone:'green'},{label:'Активные заказы',value:'96',note:'на разных этапах'},{label:'Отмены',value:'4,1%',note:'ниже августа'},{label:'Средний чек',value:'13 700 ₽',note:'+800 ₽'}]}/><section className="portal-panel"><DataTable columns={['Заказ','Клиент','Фотограф','Дата','Этап','Сумма']} rows={[[<b>#1248</b>,'Роман П.','Алина Ветрова','7 сентября',<RiskBadge tone="warning">Подтверждение</RiskBadge>,'9 900 ₽'],[<b>#1247</b>,'Мария С.','Илья Волков','6 сентября',<RiskBadge tone="success">Оплачен</RiskBadge>,'18 000 ₽'],[<b>#1246</b>,'Анна К.','Дарья Соколова','6 сентября',<RiskBadge>Съёмка прошла</RiskBadge>,'15 000 ₽'],[<b>#1245</b>,'Олег Н.','Максим Корнеев','5 сентября',<RiskBadge tone="danger">Спор</RiskBadge>,'12 500 ₽']]}/></section></>;
 if(section==='disputes') return <><MetricCards items={[{label:'Открытые споры',value:'3',note:'один высокого риска',tone:'coral'},{label:'Решено за месяц',value:'14',note:'среднее время 18 часов'},{label:'Возвращено клиентам',value:'47 800 ₽',note:'за 30 дней'}]}/><section className="dispute-grid">{[['#D-041','Олег Николаев','Фотограф опоздал на 40 минут','Высокий'],['#D-040','Мария Соколова','Не совпадает объём готовых фотографий','Средний'],['#D-039','Анна Козлова','Запрос переноса даты','Низкий']].map(([id,n,text,r],i)=><article className="portal-panel" key={id}><header><RiskBadge tone={i===0?'danger':i===1?'warning':'neutral'}>{r} риск</RiskBadge><span>{id}</span></header><h2>{text}</h2><p>{n} · заказ #{1245-i}</p><div><span><MessageSquareWarning/>Сообщений: {8-i}</span><span><Eye/>Последнее: {i+1} ч назад</span></div><footer><button>Открыть спор</button></footer></article>)}</section></>;
 if(section==='reviews') return <><Toolbar placeholder="Автор, фотограф или текст"/><section className="portal-panel"><DataTable columns={['Оценка','Автор','Получатель','Заказ','Фрагмент','Статус']} rows={[[<span className="review-stars">★★★★★</span>,'Екатерина В.','Алина Ветрова','#1231','«Получили раньше срока…»',<RiskBadge tone="success">Опубликован</RiskBadge>],[<span className="review-stars">★★☆☆☆</span>,'Олег Н.','Максим Корнеев','#1245','«Фотограф опоздал…»',<RiskBadge tone="warning">Проверка</RiskBadge>],[<span className="review-stars">★★★★★</span>,'Анна К.','Дарья Соколова','#1246','«Очень бережно с детьми…»',<RiskBadge tone="success">Опубликован</RiskBadge>]]}/></section></>;
 if(section==='locations') return <><Toolbar placeholder="Название или город" button="Добавить локацию"/><section className="portal-panel"><DataTable columns={['Локация','Город','Тип','Фотографов','Съёмок','Статус']} rows={[[<b>Москва-Сити</b>,'Москва','Город','17','184',<RiskBadge tone="success">Опубликована</RiskBadge>],[<b>Чистые пруды</b>,'Москва','Прогулка','24','263',<RiskBadge tone="success">Опубликована</RiskBadge>],[<b>Белая студия</b>,'Москва','Студия','8','42',<RiskBadge tone="warning">Проверка</RiskBadge>],[<b>Севкабель Порт</b>,'Санкт-Петербург','Город','12','96',<RiskBadge>Черновик</RiskBadge>]]}/></section></>;
 if(section==='collections') return <><section className="portal-banner"><BookOpenText/><div><span>Редакция ФотоЗаки</span><h2>Подборки помогают найти стиль, а не первое место в рейтинге</h2><p>Публикации не продаются и всегда имеют автора и прозрачные критерии.</p></div><button>Создать материал</button></section><section className="editorial-admin-grid">{[['Живой портрет','Опубликовано','12 фотографов'],['Город после дождя','Запланировано','6 локаций'],['Love story без клише','Черновик','8 фотографов']].map(([n,s,c],i)=><article className="portal-panel" key={n}><div className={`editorial-thumb mosaic-photo saved-${i+1}`}/><RiskBadge tone={i===0?'success':i===1?'warning':'neutral'}>{s}</RiskBadge><h2>{n}</h2><p>{c} · редактор Мария Ярцева</p><footer><button>Редактировать</button><a href="/collections">Предпросмотр</a></footer></article>)}</section></>;
 if(section==='finance') return <><MetricCards items={[{label:'GMV за сентябрь',value:'1,84 млн ₽',note:'+24% к августу',tone:'green'},{label:'Доход сервиса',value:'147 200 ₽',note:'после возвратов'},{label:'К выплате',value:'628 400 ₽',note:'82 фотографам'},{label:'На удержании',value:'24 900 ₽',note:'по трём спорам',tone:'coral'}]}/><section className="portal-panel"><div className="portal-panel-head"><div><span>Реестр</span><h2>Ближайшие выплаты</h2></div><button><Download/>Скачать CSV</button></div><DataTable columns={['Фотограф','Заказов','К выплате','Реквизиты','Дата','Статус']} rows={[[<b>Алина Ветрова</b>,'4','48 500 ₽','Проверены','8 сентября',<RiskBadge tone="success">Готово</RiskBadge>],[<b>Максим Корнеев</b>,'3','36 800 ₽','Проверены','8 сентября',<RiskBadge tone="success">Готово</RiskBadge>],[<b>Илья Волков</b>,'2','29 200 ₽','Нужно обновить','После проверки',<RiskBadge tone="warning">Проверка</RiskBadge>]]}/></section></>;
 if(section==='promotions') return <><MetricCards items={[{label:'Активные промокоды',value:'4',note:'126 использований'},{label:'Скидок за месяц',value:'84 600 ₽',note:'4,6% оборота'},{label:'Подарочные сертификаты',value:'18',note:'на 216 000 ₽'}]}/><section className="portal-panel"><div className="portal-panel-head"><div><span>Маркетинг</span><h2>Промокоды и сертификаты</h2></div><button><Plus/>Создать промокод</button></div><DataTable columns={['Код','Условие','Использовано','Бюджет','До','Статус']} rows={[[<b>FIRSTPHOTO</b>,'−10% на первый заказ','84 / 200','42 600 ₽','30 сентября',<RiskBadge tone="success">Активен</RiskBadge>],[<b>AUTUMN26</b>,'−1 500 ₽ от 12 000 ₽','42 / 100','63 000 ₽','15 октября',<RiskBadge tone="success">Активен</RiskBadge>],[<b>MOSCOWCITY</b>,'Локация в подарок','0 / 50','0 ₽','Черновик',<RiskBadge>Черновик</RiskBadge>]]}/></section></>;
 if(section==='reports') return <section className="report-grid">{[['Продажи и комиссия','Заказы, GMV, возвраты и доход сервиса'],['Активность фотографов','Подтверждения, сроки, отмены и рейтинг'],['Поведение клиентов','Конверсия, повторные заказы и города'],['Качество площадки','Споры, жалобы и результаты модерации']].map(([n,d],i)=><article className="portal-panel" key={n}><span><Flag/></span><h2>{n}</h2><p>{d}</p><label>Период<select><option>Последние 30 дней</option><option>Квартал</option></select></label><button><Download/>Сформировать отчёт</button></article>)}</section>;
 if(section==='settings') return <section className="admin-settings-grid"><article className="portal-panel"><ShieldAlert/><h2>Роли и доступ</h2><p>Владелец, администратор, модератор, редактор и финансовый менеджер.</p><button>Управлять ролями</button></article><article className="portal-panel"><Banknote/><h2>Комиссии</h2><p>Базовая комиссия 8%. Индивидуальные условия доступны 12 фотографам.</p><button>Настроить тарифы</button></article><article className="portal-panel"><Users/><h2>Уведомления команды</h2><p>Критические споры и сбои отправляются владельцу и дежурному администратору.</p><button>Настроить</button></article><article className="portal-panel"><BadgeCheck/><h2>Правила модерации</h2><p>Чек-листы профилей, портфолио, локаций и редакционных материалов.</p><button>Открыть правила</button></article><article className="portal-panel wide"><div className="portal-panel-head"><div><span>Безопасность</span><h2>Журнал действий</h2></div><a href="/admin/audit-log">Открыть журнал</a></div><p>Каждое изменение доступа, выплаты, заказа или модерации сохраняется с автором и временем.</p></article></section>;
 if(section==='audit-log') return <section className="portal-panel"><DataTable columns={['Время','Администратор','Действие','Объект','Результат']} rows={[["Сегодня, 11:42",'Роман Проскурнин','Одобрил профиль','Виктория Лебедева',<RiskBadge tone="success">Успешно</RiskBadge>],["Сегодня, 10:18",'Мария Ярцева','Опубликовала подборку','Живой портрет',<RiskBadge tone="success">Успешно</RiskBadge>],["Вчера, 19:05",'Система','Ограничила выплату','Спор #D-041',<RiskBadge tone="warning">На проверке</RiskBadge>]]}/></section>;
 return <section className="portal-panel"><h2>Раздел не найден</h2><p>Вернитесь на главную страницу администрирования.</p></section>;
}

export default async function AdminSectionPage({params}:{params:Promise<{section:string[]}>}){const {section}=await params;const key=section.join('/');return <AdminShell title={names[key]||'Администрирование'} current={`/admin/${key}`} action={key==='moderation'?undefined:{href:'/admin/moderation',label:'Очередь модерации'}}><AdminContent section={key}/></AdminShell>}
