import { ArrowRight, CalendarDays, Camera, CheckCircle2, Clock3, Heart, Images, MessageCircle, Settings, Star } from 'lucide-react';
import { Logo } from '../../_components/site-shell';

export default function ClientDashboard() {
  return <main className="dashboard-page"><aside className="dash-sidebar"><Logo/><nav><a className="active" href="/dashboard/client"><CalendarDays/>Обзор</a><a href="/dashboard/client/orders"><Camera/>Мои съёмки</a><a href="/dashboard/client/favorites"><Heart/>Избранное</a><a href="/dashboard/client/galleries"><Images/>Галереи</a><a href="/dashboard/client/messages"><MessageCircle/>Сообщения <i>2</i></a></nav><div className="sidebar-bottom"><a href="/dashboard/client/settings"><Settings/>Настройки</a><div className="user-mini"><span>РП</span><div><b>Роман</b><small>Клиент · 4,9 ★</small></div></div></div></aside>
    <section className="dash-content"><header className="dash-top"><div><span>Четверг, 4 сентября</span><h1>Здравствуйте, Роман</h1></div><a href="/search">Найти фотографа <ArrowRight size={17}/></a></header>
      <article className="next-shoot"><div className="next-photo mosaic-photo"/><div className="next-copy"><span className="status pending">Ожидает подтверждения</span><h2>Рассвет на крыше</h2><p>с Алиной Ветровой</p><div className="next-meta"><span><CalendarDays size={17}/><b>7 сентября</b><small>суббота</small></span><span><Clock3 size={17}/><b>06:00–07:00</b><small>60 минут</small></span><span><Camera size={17}/><b>Москва-Сити</b><small>точка встречи внутри</small></span></div><footer><a href="/dashboard/client/orders/1248">Открыть заказ</a><button>Написать фотографу</button></footer></div></article>
      <div className="dash-two"><section><div className="dash-section-head"><h2>Ваши съёмки</h2><button>Все</button></div><div className="order-list"><a href="/dashboard/client/orders/1248"><span className="order-icon upcoming"><CalendarDays/></span><div><b>Рассвет на крыше</b><small>7 сентября · Алина Ветрова</small></div><span className="status pending">Ожидает</span><ArrowRight/></a><a href="/gallery/demo"><span className="order-icon ready"><CheckCircle2/></span><div><b>Love story на Чистых прудах</b><small>12 августа · Максим Корнеев</small></div><span className="status complete">Готово</span><ArrowRight/></a></div></section><aside className="client-rating"><Star size={23} fill="currentColor"/><span>Ваш рейтинг</span><strong>4,9</strong><p>3 отзыва от фотографов</p><small>Пунктуальность и лёгкость общения помогают фотографам быстрее подтверждать заявки.</small></aside></div>
    </section></main>;
}
