import { Bell, CalendarDays, Camera, CheckCircle2, CreditCard, FolderHeart, Heart, Images, MapPin, MessageCircle, Settings, Star, UserRound } from 'lucide-react';
import { DataTable, EmptyState, MetricCards, PortalShell, type PortalNavItem } from '../../../_components/portal-shell';

const nav: PortalNavItem[] = [
  {href:'/dashboard/client',label:'Обзор',icon:<CalendarDays/>},
  {href:'/dashboard/client/orders',label:'Мои съёмки',icon:<Camera/>,badge:'2'},
  {href:'/dashboard/client/favorites',label:'Избранное',icon:<Heart/>},
  {href:'/dashboard/client/saved-shoots',label:'Идеи съёмок',icon:<FolderHeart/>},
  {href:'/dashboard/client/galleries',label:'Галереи',icon:<Images/>},
  {href:'/dashboard/client/messages',label:'Сообщения',icon:<MessageCircle/>,badge:'2'},
  {href:'/dashboard/client/notifications',label:'Уведомления',icon:<Bell/>},
  {href:'/dashboard/client/payments',label:'Оплата и чеки',icon:<CreditCard/>},
  {href:'/dashboard/client/profile',label:'Мой профиль',icon:<UserRound/>},
];

const names: Record<string,string> = {orders:'Мои съёмки',favorites:'Избранные фотографы','saved-shoots':'Сохранённые идеи',galleries:'Мои галереи',messages:'Сообщения',notifications:'Уведомления',payments:'Оплата и чеки',profile:'Профиль',reviews:'Мои отзывы',rating:'Рейтинг клиента',settings:'Настройки'};

function ClientContent({section}:{section:string}){
  if(section==='orders') return <><MetricCards items={[{label:'Ближайшая съёмка',value:'7 сентября',note:'Москва-Сити · 06:00',tone:'coral'},{label:'Активные заказы',value:'2',note:'один ждёт подтверждения'},{label:'Завершено',value:'4',note:'за последние 12 месяцев'}]}/><section className="portal-panel"><div className="portal-panel-head"><div><span>История заказов</span><h2>Все съёмки</h2></div><div className="portal-tabs"><button className="active">Все</button><button>Предстоящие</button><button>Завершённые</button></div></div><DataTable columns={['Съёмка','Фотограф','Дата','Статус','Стоимость']} rows={[[<a href="/dashboard/client/orders/1248"><b>Рассвет на крыше</b><small>Москва-Сити</small></a>,'Алина Ветрова','7 сентября',<i className="status pending">Ожидает</i>,'9 900 ₽'],[<a href="/gallery/demo"><b>Love story</b><small>Чистые пруды</small></a>,'Максим Корнеев','12 августа',<i className="status complete">Готово</i>,'12 500 ₽'],[<span><b>Семейная прогулка</b><small>Коломенское</small></span>,'Дарья Соколова','28 мая','Завершён','15 000 ₽']]}/></section></>;
  if(section==='favorites') return <><MetricCards items={[{label:'Сохранено',value:'6',note:'фотографов'},{label:'Свободны 7 сентября',value:'3',note:'можно забронировать',tone:'green'},{label:'Средняя цена',value:'12 400 ₽',note:'за часовую съёмку'}]}/><section className="portal-card-grid">{['Алина Ветрова','Максим Корнеев','Дарья Соколова'].map((n,i)=><article key={n}><div className={`saved-photo mosaic-photo saved-${i+1}`}/><span><Star fill="currentColor"/> {['4,98','4,94','4,91'][i]}</span><h2>{n}</h2><p>Портрет · Love story · Москва</p><footer><a href="/photographers/alina-vetrova">Открыть профиль</a><button aria-label="Убрать из избранного"><Heart fill="currentColor"/></button></footer></article>)}</section></>;
  if(section==='saved-shoots') return <section className="portal-card-grid ideas">{['Рассвет на крыше','Город после дождя','Love story без позирования'].map((n,i)=><article key={n}><div className={`saved-photo mosaic-photo saved-${i+1}`}/><span>Сценарий на 60–90 минут</span><h2>{n}</h2><p>Маршрут, референсы и подходящие фотографы уже собраны.</p><footer><a href="/shoots/rooftop-sunrise">Посмотреть идею</a></footer></article>)}</section>;
  if(section==='galleries') return <><section className="portal-banner"><Images/><div><span>Новая галерея</span><h2>Love story на Чистых прудах</h2><p>48 фотографий готовы к просмотру. Ссылка действует до 12 ноября.</p></div><a href="/gallery/demo">Открыть галерею</a></section><section className="portal-panel"><div className="portal-panel-head"><div><span>Ваш архив</span><h2>Все галереи</h2></div></div><DataTable columns={['Галерея','Фотограф','Фотографий','Хранение','Действие']} rows={[[<b>Love story на Чистых прудах</b>,'Максим Корнеев','48','до 12 ноября',<a href="/gallery/demo">Открыть</a>],[<b>Семейная прогулка</b>,'Дарья Соколова','76','архивирована','Продлить']]}/></section></>;
  if(section==='messages') return <section className="messenger"><aside><label><MessageCircle/><input placeholder="Поиск в сообщениях"/></label>{['Алина Ветрова','Максим Корнеев','Поддержка ФотоЗаки'].map((n,i)=><button className={i===0?'active':''} key={n}><span>{n.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b>{n}</b><small>{i===0?'Да, встречаемся у башни…':i===1?'Фотографии готовы!':'Чем можем помочь?'}</small></div>{i<2&&<i>{i+1}</i>}</button>)}</aside><div className="chat"><header><span>АВ</span><div><b>Алина Ветрова</b><small>обычно отвечает за 12 минут</small></div></header><div className="chat-body"><p className="theirs">Здравствуйте! Подтверждаю съёмку 7 сентября. Давайте встретимся у башни Федерация.</p><p className="ours">Отлично, будем вовремя. Возьмём светлую одежду.</p><p className="theirs">Супер — она хорошо сработает на рассвете. За день пришлю памятку.</p></div><footer><input placeholder="Написать сообщение…"/><button>Отправить</button></footer></div></section>;
  if(section==='notifications') return <section className="portal-panel"><div className="portal-panel-head"><div><span>Последние события</span><h2>Уведомления</h2></div><button>Отметить всё прочитанным</button></div><div className="notification-list">{[[Camera,'Алина подтвердила детали маршрута','Сегодня, 10:24'],[MessageCircle,'Новое сообщение от Максима','Вчера, 18:42'],[CheckCircle2,'Галерея готова к просмотру','12 августа'],[Star,'Оцените прошедшую съёмку','13 августа']].map(([Icon,t,d]:any)=><article key={t}><span><Icon/></span><div><b>{t}</b><small>{d}</small></div></article>)}</div></section>;
  if(section==='payments') return <><MetricCards items={[{label:'Оплачено за год',value:'37 400 ₽',note:'3 заказа'},{label:'Возвраты',value:'0 ₽',note:'без отмен'},{label:'Сохранённая карта',value:'•••• 4242',note:'Visa'}]}/><section className="portal-panel"><div className="portal-panel-head"><div><span>Финансы</span><h2>Платежи и чеки</h2></div><button>Добавить карту</button></div><DataTable columns={['Дата','Назначение','Способ','Сумма','Чек']} rows={[['4 сентября','Предоплата · Рассвет на крыше','•••• 4242','1 980 ₽','Скачать'],['12 августа','Love story · полный расчёт','СБП','12 500 ₽','Скачать'],['28 мая','Семейная прогулка','•••• 4242','15 000 ₽','Скачать']]}/></section></>;
  if(section==='profile') return <section className="profile-settings portal-panel"><div className="portal-panel-head"><div><span>Личные данные</span><h2>Профиль клиента</h2></div><span className="profile-score"><Star fill="currentColor"/> 4,9</span></div><div className="settings-avatar"><span>РП</span><button>Изменить фотографию</button></div><div className="settings-grid"><label>Имя<input defaultValue="Роман"/></label><label>Фамилия<input defaultValue="Проскурнин"/></label><label>Электронная почта<input defaultValue="roman@proskurnin.ru"/></label><label>Телефон<input defaultValue="+7 999 000-00-00"/></label><label className="wide">О себе<textarea defaultValue="Люблю живые городские кадры без сложного позирования."/></label></div><footer><button>Сохранить изменения</button></footer></section>;
  if(section==='reviews') return <section className="portal-panel"><div className="portal-panel-head"><div><span>После завершённых заказов</span><h2>Мои отзывы</h2></div></div><div className="review-list"><article><span className="review-stars">★★★★★</span><h3>Максим Корнеев</h3><p>Очень легко общаться, фотографии получили раньше срока. Особенно понравился маршрут.</p><small>Заказ подтверждён · 12 августа</small></article><article className="review-needed"><Star/><h3>Оцените семейную прогулку</h3><p>Ваш отзыв поможет другим клиентам выбрать фотографа.</p><button>Оставить отзыв</button></article></div></section>;
  if(section==='rating') return <><section className="rating-hero"><Star fill="currentColor"/><div><span>Ваш рейтинг клиента</span><strong>4,9</strong><p>3 оценки от фотографов</p></div></section><section className="portal-panel rating-factors"><h2>Из чего складывается рейтинг</h2><div><span><CheckCircle2/><b>Пунктуальность</b><small>5,0</small></span><span><MessageCircle/><b>Общение</b><small>4,8</small></span><span><CreditCard/><b>Оплата вовремя</b><small>5,0</small></span></div><p>Рейтинг виден фотографу при подтверждении заявки. Оспорить оценку можно через поддержку.</p></section></>;
  if(section==='settings') return <section className="portal-panel profile-settings"><div className="portal-panel-head"><div><span>Предпочтения</span><h2>Настройки</h2></div></div><div className="toggle-list"><label><span><b>Напоминания о съёмках</b><small>За день и за два часа</small></span><input type="checkbox" defaultChecked/></label><label><span><b>Новые сообщения</b><small>Письмо и push-уведомление</small></span><input type="checkbox" defaultChecked/></label><label><span><b>Идеи и подборки</b><small>Не чаще одного раза в неделю</small></span><input type="checkbox"/></label></div><a className="danger-link" href="/account/sessions">Устройства и безопасность</a></section>;
  return <EmptyState icon={<Camera/>} title="Раздел готовится" text="Здесь появятся ваши данные после первой съёмки." href="/search" action="Найти фотографа"/>;
}

export default async function ClientSectionPage({params}:{params:Promise<{section:string[]}>}){const {section}=await params; const key=section.join('/'); return <PortalShell role="Кабинет клиента" name="Роман Проскурнин" initials="РП" subtitle="Клиент · рейтинг 4,9" title={names[key]||'Личный кабинет'} current={`/dashboard/client/${key}`} nav={nav} action={{href:'/search',label:'Найти фотографа'}}><ClientContent section={key}/></PortalShell>}
