import { ArrowLeft, CalendarDays, Check, Clock3, CloudSun, MapPin, Navigation, ShieldCheck, Sparkles, Star } from 'lucide-react';
import { SiteFooter, SiteHeader } from '../../_components/site-shell';

export default function ShootDetailPage() {
  return <main><SiteHeader compact/><div className="shell crumbs"><a href="/shoots"><ArrowLeft size={15}/> Все идеи съёмок</a><span>Москва · На улице</span></div>
    <section className="shoot-detail-hero shell"><div className="shoot-detail-photo mosaic-photo"/><div className="shoot-detail-copy"><span className="eyebrow"><Sparkles size={14}/> Бестселлер недели</span><h1>Рассвет<br/><em>на крыше</em></h1><p>Город только просыпается, мягкий свет отражается в стекле небоскрёбов, а Москва остаётся фоном вашей истории.</p><div className="detail-pills"><span><Clock3 size={16}/> 60 минут</span><span><MapPin size={16}/> Москва-Сити</span><span><CloudSun size={16}/> Лучший свет: 05:30–07:30</span></div></div></section>
    <section className="detail-body shell"><div><div className="content-block"><span className="kicker">Что входит</span><h2>Вам остаётся только приехать</h2><div className="included-grid"><span><Check size={17}/><b>Консультация</b><small>Поможем с образом и одеждой</small></span><span><Check size={17}/><b>Маршрут</b><small>Три точки в пешей доступности</small></span><span><Check size={17}/><b>50+ фотографий</b><small>Цветокоррекция и ретушь</small></span><span><Check size={17}/><b>Закрытая галерея</b><small>Будет доступна после запуска функции</small></span></div></div>
      <div className="content-block location-card"><div className="location-map"><Navigation size={27}/><span>Москва-Сити</span><small>точное место после бронирования</small></div><div><span className="kicker">Локация</span><h2>Башни, набережная и чистая геометрия</h2><p>Маршрут не требует разрешений. Фотограф проверит погоду накануне и предложит крытую альтернативу, если понадобится.</p></div></div>
      <div className="content-block"><h2>Кто снимает этот сценарий</h2><div className="maker-row"><div className="maker-avatar mosaic-photo"/><div><h3>Алина Ветрова</h3><p>Портреты · Love story</p><span><Star size={15} fill="currentColor"/> 4,98 · 86 отзывов</span></div><a href="/photographers/alina-vetrova">Профиль фотографа</a></div></div>
    </div><aside className="booking-summary sticky"><span>Съёмка под ключ</span><strong>от 9 900 ₽</strong><p>Итоговая цена зависит от выбранного фотографа.</p><label>Дата<select><option>7 сентября, суббота</option><option>8 сентября, воскресенье</option></select></label><label>Время<select><option>06:00</option><option>06:30</option><option>07:00</option></select></label><a href="/booking">Выбрать фотографа</a><small><ShieldCheck size={15}/> Безопасная предоплата</small></aside></section><SiteFooter/></main>;
}
