import { ArrowLeft, ArrowRight, Car, Check, Clock3, CloudRain, MapPin, Navigation, ShieldCheck, SunMedium, Users } from 'lucide-react';
import { PhotoCard } from '../../_components/photo-card';
import { SiteFooter, SiteHeader } from '../../_components/site-shell';
import { locations, photographers } from '../../data';

export default function LocationPage(){const l=locations[0];return <main><SiteHeader compact/><div className="shell crumbs"><a href="/locations"><ArrowLeft/>Все локации</a><span>Москва · Город</span></div>
  <section className="location-detail-hero shell"><div className="location-detail-photo mosaic-photo"/><div><span className="eyebrow"><SunMedium/> Идеально на рассвете</span><h1>{l.name}</h1><p>Стекло, отражения и чистая архитектура. Подходит для портретов, love story и контента для личного бренда.</p><div className="location-stats"><span><b>{l.shoots}</b>съёмок через ФотоЗаку</span><span><b>{l.photographers}</b>фотографов знают место</span><span><b>0 ₽</b>стоимость локации</span></div><a className="primary-link" href="/search">Найти фотографа здесь <ArrowRight/></a></div></section>
  <section className="location-detail-body shell"><div><div className="content-block"><span className="kicker">Практическая информация</span><h2>Всё известно до поездки</h2><div className="fact-grid"><span><SunMedium/><b>Лучший свет</b><small>{l.best}</small></span><span><ShieldCheck/><b>Разрешение</b><small>{l.permit}</small></span><span><Car/><b>Как добраться</b><small>{l.parking}</small></span><span><CloudRain/><b>Если дождь</b><small>{l.indoor}</small></span></div></div><div className="content-block route-card"><div className="route-map"><MapPin/><i/><Navigation/></div><div><span className="kicker">Маршрут на 60 минут</span><h2>Три точки без спешки</h2><ol><li><b>Набережная</b><small>мягкий свет и отражение воды</small></li><li><b>Стеклянный переход</b><small>графичные портреты</small></li><li><b>Башня Федерация</b><small>финальные кадры в движении</small></li></ol></div></div></div><aside className="location-book"><Users/><h3>17 фотографов свободны здесь 7 сентября</h3><p>Они уже снимали в Москва-Сити и знают лучший маршрут.</p><a href="/search">Показать фотографов</a><small><Check/> Локация включена в итоговую цену</small></aside></section>
  <section className="location-photographers shell"><div className="section-heading"><div><span className="kicker">Знают эту локацию</span><h2>Фотографы с готовым маршрутом</h2></div></div><div className="cards-grid">{photographers.slice(0,3).map((p)=><PhotoCard person={p} key={p.slug}/>)}</div></section><SiteFooter/></main>}
