import { BadgeCheck, BriefcaseBusiness, CalendarDays, Camera, ChartNoAxesCombined, CircleDollarSign, Images, MapPin, MessageCircle, PackageCheck, Star, Upload, UserRound, Users } from 'lucide-react';
import { DataTable, EmptyState, MetricCards, PortalShell, type PortalNavItem } from '../../../_components/portal-shell';

const nav: PortalNavItem[]=[
 {href:'/dashboard/photographer',label:'Календарь',icon:<CalendarDays/>},
 {href:'/dashboard/photographer/orders',label:'Заказы и заявки',icon:<BriefcaseBusiness/>,badge:'3'},
 {href:'/dashboard/photographer/messages',label:'Сообщения',icon:<MessageCircle/>,badge:'3'},
 {href:'/dashboard/photographer/clients',label:'Клиенты',icon:<Users/>},
 {href:'/dashboard/photographer/portfolio',label:'Портфолио',icon:<Images/>},
 {href:'/dashboard/photographer/services',label:'Услуги и цены',icon:<PackageCheck/>},
 {href:'/dashboard/photographer/locations',label:'Мои локации',icon:<MapPin/>},
 {href:'/dashboard/photographer/galleries',label:'Галереи',icon:<Upload/>},
 {href:'/dashboard/photographer/finance',label:'Финансы',icon:<CircleDollarSign/>},
 {href:'/dashboard/photographer/analytics',label:'Аналитика',icon:<ChartNoAxesCombined/>},
 {href:'/dashboard/photographer/profile',label:'Профиль',icon:<UserRound/>},
];
const names:Record<string,string>={orders:'Заказы и заявки',messages:'Сообщения',clients:'Клиенты',portfolio:'Портфолио',services:'Услуги и цены',locations:'Мои локации',galleries:'Клиентские галереи',finance:'Финансы и выплаты',reviews:'Отзывы',analytics:'Аналитика профиля',profile:'Публичный профиль',notifications:'Уведомления',settings:'Настройки',onboarding:'Начало работы'};

function PhotographerContent({section}:{section:string}){
 if(section==='orders') return <><MetricCards items={[{label:'Новые заявки',value:'3',note:'нужно ответить сегодня',tone:'coral'},{label:'Подтверждено',value:'6',note:'на ближайшие 14 дней',tone:'green'},{label:'Средний чек',value:'14 800 ₽',note:'+8% за месяц'}]}/><section className="portal-panel"><div className="portal-panel-head"><div><span>Рабочая очередь</span><h2>Заказы и заявки</h2></div><div className="portal-tabs"><button className="active">Все</button><button>Новые</button><button>В работе</button></div></div><DataTable columns={['Клиент','Съёмка','Дата','Статус','Сумма']} rows={[[<a href="/dashboard/photographer/orders/1248"><b>Роман Проскурнин</b><small>рейтинг 4,9</small></a>,'Рассвет на крыше','7 сентября',<i className="status pending">Новая заявка</i>,'9 900 ₽'],['Анна и Михаил','Love story','8 сентября',<i className="status complete">Подтверждено</i>,'12 500 ₽'],['Мария Соколова','Личный бренд','9 сентября','Ожидает оплаты','18 000 ₽'],['Семья Волковых','Семейная','12 сентября','Подтверждено','15 000 ₽']]}/></section></>;
 if(section==='clients') return <section className="portal-panel"><div className="portal-panel-head"><div><span>CRM фотографа</span><h2>Клиенты</h2></div><button>Добавить клиента</button></div><DataTable columns={['Клиент','Последняя съёмка','Заказов','Рейтинг','Контакт']} rows={[[<b>Екатерина Волкова</b>,'2 сентября','3','5,0','Написать'],[<b>Роман Проскурнин</b>,'Новая заявка','1','4,9','Открыть'],[<b>Анна и Михаил</b>,'12 августа','2','5,0','Написать'],[<b>Мария Соколова</b>,'4 июля','4','4,8','Написать']]}/></section>;
 if(section==='messages') return <section className="messenger"><aside><label><MessageCircle/><input placeholder="Клиент или заказ"/></label>{['Роман Проскурнин','Анна и Михаил','Мария Соколова'].map((n,i)=><button className={i===0?'active':''} key={n}><span>{n.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b>{n}</b><small>{i===0?'Возьмём светлую одежду':'Спасибо, всё понятно!'}</small></div>{i===0&&<i>2</i>}</button>)}</aside><div className="chat"><header><span>РП</span><div><b>Роман Проскурнин</b><small>заказ №1248 · рейтинг 4,9</small></div></header><div className="chat-body"><p className="theirs">Здравствуйте! Хотим спокойную прогулку без сложных поз.</p><p className="ours">Отлично. Предлагаю начать у башни Федерация — там в 06:00 мягкий свет.</p><p className="theirs">Подходит. Возьмём светлую одежду.</p></div><footer><input placeholder="Ответить клиенту…"/><button>Отправить</button></footer></div></section>;
 if(section==='portfolio') return <><section className="portal-banner"><Upload/><div><span>Сильное портфолио</span><h2>Загружайте серии, а не случайные кадры</h2><p>В профиле опубликовано 24 работы. Рекомендуем добавить одну свежую серию.</p></div><button>Загрузить серию</button></section><section className="portfolio-manager">{Array.from({length:9},(_,i)=><article className={`mosaic-photo portfolio-${i%6}`} key={i}><span>{i<3?'Серия «Рассвет»':'Портрет'}</span><button>•••</button></article>)}</section></>;
 if(section==='services') return <><MetricCards items={[{label:'Активные пакеты',value:'3',note:'видны в профиле'},{label:'Самый популярный',value:'Прогулка',note:'62% заказов',tone:'green'},{label:'Средний чек',value:'14 800 ₽',note:'с учётом дополнений'}]}/><section className="portal-card-grid packages">{[['Экспресс','60 минут','9 900 ₽'],['Прогулка','90 минут','14 900 ₽'],['История','2 часа','19 900 ₽']].map(([n,d,p],i)=><article key={n}><span>Пакет {i+1}</span><h2>{n}</h2><strong>{p}</strong><ul><li>{d} съёмки</li><li>{40+i*20} фотографий</li><li>готовность за {5+i*2} дней</li></ul><footer><button>Редактировать</button></footer></article>)}</section><button className="portal-add">+ Добавить пакет</button></>;
 if(section==='locations') return <section className="portal-panel"><div className="portal-panel-head"><div><span>Ваши маршруты</span><h2>Локации</h2></div><button>Добавить локацию</button></div><DataTable columns={['Локация','Опыт','Лучшее время','Доплата','Статус']} rows={[[<b>Москва-Сити</b>,'18 съёмок','05:30–08:00','0 ₽','Опубликована'],[<b>Чистые пруды</b>,'12 съёмок','07:00–10:00','0 ₽','Опубликована'],[<b>Студия 18</b>,'9 съёмок','весь день','от 2 500 ₽','Опубликована'],[<b>Белая студия</b>,'3 съёмки','весь день','от 3 000 ₽','Черновик']]}/></section>;
 if(section==='galleries') return <><section className="portal-banner"><Images/><div><span>Передача результата</span><h2>Новая клиентская галерея</h2><p>Загрузите превью, задайте срок хранения и отправьте защищённую ссылку.</p></div><a href="/dashboard/photographer/galleries/new">Создать галерею</a></section><section className="portal-panel"><DataTable columns={['Галерея','Клиент','Файлов','Доступ','Хранение']} rows={[[<a href="/gallery/demo"><b>Love story · Чистые пруды</b></a>,'Анна и Михаил','48','Открыта','до 12 ноября'],['Семейная прогулка','Волковы','76','По коду','до 28 октября'],['Личный бренд','Мария Соколова','124','Черновик','не отправлена']]}/></section></>;
 if(section==='finance') return <><MetricCards items={[{label:'Доступно к выплате',value:'48 500 ₽',note:'выплата 8 сентября',tone:'green'},{label:'В работе',value:'61 300 ₽',note:'по подтверждённым заказам'},{label:'Комиссия сервиса',value:'8%',note:'текущий тариф'}]}/><section className="portal-panel"><div className="portal-panel-head"><div><span>Движение средств</span><h2>Операции</h2></div><button>Настроить выплаты</button></div><DataTable columns={['Дата','Заказ','Клиент','Сумма','Статус']} rows={[['4 сентября','#1248 · Рассвет','Роман','9 108 ₽','Зарезервировано'],['2 сентября','#1231 · Портрет','Екатерина','16 560 ₽','К выплате'],['29 августа','#1214 · Love story','Анна и Михаил','11 500 ₽','Выплачено']]}/></section></>;
 if(section==='reviews') return <><MetricCards items={[{label:'Рейтинг',value:'4,98',note:'86 подтверждённых отзывов',tone:'green'},{label:'Коммуникация',value:'5,0',note:'средняя оценка'},{label:'Сроки',value:'4,9',note:'средняя оценка'}]}/><section className="review-list"><article><span className="review-stars">★★★★★</span><h3>Екатерина Волкова</h3><p>Алина помогла расслабиться и поймала живые моменты. Фотографии получили раньше обещанного.</p><small>Подтверждённый заказ · 2 сентября</small><button>Ответить</button></article><article><span className="review-stars">★★★★★</span><h3>Анна и Михаил</h3><p>Маршрут был продуман до мелочей, а сама прогулка прошла очень легко.</p><small>Подтверждённый заказ · 12 августа</small><button>Ответить</button></article></section></>;
 if(section==='analytics') return <><MetricCards items={[{label:'Просмотры профиля',value:'2 418',note:'+18% за 30 дней',tone:'green'},{label:'Добавили в избранное',value:'186',note:'7,7% просмотров'},{label:'Заявки',value:'42',note:'конверсия 1,7%'},{label:'Подтверждение',value:'98%',note:'выше среднего'}]}/><section className="portal-panel analytics-panel"><div className="portal-panel-head"><div><span>Последние 30 дней</span><h2>Просмотры и заявки</h2></div><select><option>30 дней</option><option>90 дней</option></select></div><div className="bar-chart">{[38,52,45,68,62,79,70,88,76,95,82,100].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div><div className="analytics-sources"><span><b>47%</b>Поиск по дате</span><span><b>31%</b>Подборки</span><span><b>22%</b>Прямые переходы</span></div></section></>;
 if(section==='profile') return <section className="portal-panel profile-settings"><div className="portal-panel-head"><div><span>Видно клиентам</span><h2>Публичный профиль</h2></div><a href="/photographers/alina-vetrova">Посмотреть профиль</a></div><div className="settings-grid"><label>Имя и фамилия<input defaultValue="Алина Ветрова"/></label><label>Город<select defaultValue="Москва"><option>Москва</option></select></label><label>Специализация<input defaultValue="Портрет · Love story · Контент"/></label><label>Срок готовности<input defaultValue="5–7 дней"/></label><label className="wide">О себе<textarea defaultValue="Помогаю сохранить живые моменты без сложного позирования. Подскажу маршрут, одежду и лучшее время."/></label></div><footer><button>Сохранить и отправить на проверку</button></footer></section>;
 if(section==='notifications') return <section className="portal-panel"><div className="notification-list">{[[BriefcaseBusiness,'Новая заявка на 7 сентября','Ответьте в течение двух часов'],[CircleDollarSign,'Выплата 16 560 ₽ отправлена','Сегодня, 09:10'],[Star,'Новый отзыв: 5,0','Вчера, 18:42'],[BadgeCheck,'Портфолио прошло проверку','2 сентября']].map(([Icon,t,d]:any)=><article key={t}><span><Icon/></span><div><b>{t}</b><small>{d}</small></div></article>)}</div></section>;
 if(section==='settings') return <section className="portal-panel profile-settings"><div className="portal-panel-head"><div><span>Работа сервиса</span><h2>Настройки фотографа</h2></div></div><div className="toggle-list"><label><span><b>Автоподтверждение свободных слотов</b><small>Для клиентов с рейтингом от 4,8</small></span><input type="checkbox"/></label><label><span><b>Новые заявки</b><small>Push, email и Telegram</small></span><input type="checkbox" defaultChecked/></label><label><span><b>Напоминать о сроке готовности</b><small>За 48 и 12 часов</small></span><input type="checkbox" defaultChecked/></label></div></section>;
 if(section==='onboarding') return <section className="onboarding-panel"><div className="onboarding-progress"><span>Шаг 3 из 5</span><i><b style={{width:'60%'}}/></i></div><BadgeCheck/><h1>Подготовим профиль к публикации</h1><p>Заполните основные данные — редактор проверит их в течение одного рабочего дня.</p><div className="onboarding-steps"><span className="done">1<b>Контакты</b></span><span className="done">2<b>Опыт</b></span><span className="active">3<b>Портфолио</b></span><span>4<b>Услуги</b></span><span>5<b>Проверка</b></span></div><button>Продолжить заполнение</button></section>;
 return <EmptyState icon={<Camera/>} title="Раздел готовится" text="Здесь появятся рабочие данные фотографа." href="/dashboard/photographer" action="Вернуться в календарь"/>;
}

export default async function PhotographerSectionPage({params}:{params:Promise<{section:string[]}>}){const {section}=await params;const key=section.join('/');return <PortalShell role="Кабинет фотографа" name="Алина Ветрова" initials="АВ" subtitle="Фотограф · рейтинг 4,98" title={names[key]||'Рабочий кабинет'} current={`/dashboard/photographer/${key}`} nav={nav} action={{href:'/dashboard/photographer/orders',label:'Открыть заявки'}}><PhotographerContent section={key}/></PortalShell>}
